### ISSUE TITLE
Extragere si importare de date in explorer pentru un interval de timp luna / an.

### ISSUE THREAD

**Issue by elaur** [ciocan/sicap-parser#2]
Exista o pozibilitate de extragere doar pentru o anumita luna in parte, spre exemplu doar "noiembrie 2020" sau doar anul respectiv in parte ?

Am ramas putin confuz de procesul de extragere, nu am inteles unde se salveaza fisierul final, ce face acea -a arhiva... si cum adaugam acesta exportare din parse in pasi mai marunti in kibana pentru un rezultat final.

Multumesc,

**Comment by ciocan** [comment]
Momentan poate descarca informatiile doar pentru o zi anume.

Daca vrei anumite perioade, poti crea un script bash (sau nodejs, etc) ce face un loop pentru perioada dorita si executa scriptul secvential pentru fiecre data din acea perioada.

Datele salvate se salveaza automat in Elasticsearch iar de acolo se pot vizualiza, exporta, etc cu Kibana conectat la acea instanta de elasticsearch.

Parametrul -a se refera la siteul vechi seap (arhiva) pentru ca api-ul se gasesrte la alt url. 
https://istoric.e-licitatie.ro/pub
