### ISSUE TITLE
Descarcare documente

### ISSUE THREAD

**Issue by andrei-zmf** [ciocan/sicap-parser#4]
Salutare,

Exista posibilitatea de a descarca si documentele din licitatii? Ma poate ajuta cineva cu un API?
Din site am observat se face urmatorul request:

Tip: GET
URL: https://e-licitatie.ro/api-pub/files/noticedoc/cad0a36e192c425188eabccd9964312e
Headers: 
- Referer: https://e-licitatie.ro/pub/notices/c-notice/v2/view/100051629
- Culture: ro-RO

Dar rulat separat returneaza 500 Critical Exception - An error occurred, please try again or contact the administrator.

Daca a reusit cineva sa ia si documentele as aprecia orice informatie.

Multumesc!

**Comment by ciocan** [comment]
Salut, scuze nu am mai fost activ pe proiect de ceva vreme.
Ai reusit ceva?
