### ISSUE TITLE
ConnectionError: connect ECONNREFUSED 127.0.0.1:9200 (Elasticsearch)

### ISSUE THREAD

**Issue by pax** [ciocan/sicap-parser#5]
am instalat pe windows (node v14.18.1) și mac (node v14.15.5)
la rulare îmi apare aceeași eroare:

```
ConnectionError: connect ECONNREFUSED 127.0.0.1:9200
    at ClientRequest.<anonymous> (***/sicap-parser/node_modules/@elastic/elasticsearch/lib/Connection.js:107:18)
```

deduc că la 127.0.0.1:9200 ar trebui să răspundă o instanță de Elasticsearch – teoretic ar trebui lansată automat de script?

**Comment by ciocan** [comment]
```
code => code?.replace(/ro/i, "")
```
optional chaining a intrat in node v14
https://medium.com/nmc-techblog/new-js-features-in-node-js-v14-0-6d833c7665b6

cel mai bine instaleaza ultima versiune (v16 sau 17 sa fii sigur)
